### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by posix4e** [highperformancecoder/minsky#2]
I was able to get ecolab installed. Still working on getting the full tests to run, however, now I have a problem with minksky itself, but I think I'm close.

....
g++ -c -fPIC -I. -I/home/vagrant/usr/ecolab/include -DHASH_TCL_hash -DHAVE_LONGLONG -DTR1 -I/home/vagrant/usr/ecolab/include -I/home/vagrant/usr/include -I/usr/local/include -I/opt/local/include -I/usr/X11R6/include -DZLIB -DXDR_PACK -DCONTIGUOUS -I/usr/include/tcl8.6 -DECOLAB_LIB=\"/home/vagrant/usr/ecolab/include\" -DNDEBUG -I/home/vagrant/usr/ecolab/include -std=c++11 -Ischema -Iengine -IGUI -O3 -UECOLAB_LIB -DECOLAB_LIB=\"library\" -pthread -I/usr/include/librsvg-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/libpng12 -I/usr/include/pixman-1 -I/usr/include/freetype2   -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -O3 -o tclmain.o tclmain.cc

tclmain.cc:56:3: error: ‘Tk_Window’ does not name a type
   Tk_Window mainWin=0;
   ^
tclmain.cc: In function ‘int main(int, char**)’:
tclmain.cc:123:10: error: ‘mainWin’ was not declared in this scope
   while (mainWin) /* we are running GUI mode */
          ^
tclmain.cc: In function ‘void GUI(int, const char**)’:
tclmain.cc:142:23: error: ‘Tk_Init’ was not declared in this scope
   if (Tk_Init(interp())==TCL_ERROR || Tktable_Init(interp())==TCL_ERROR)
                       ^
tclmain.cc:158:3: error: ‘mainWin’ was not declared in this scope
   mainWin = Tk_MainWindow(interp());
   ^
tclmain.cc:158:35: error: ‘Tk_MainWindow’ was not declared in this scope
   mainWin = Tk_MainWindow(interp());
                                   ^
tclmain.cc: In function ‘void exit_ecolab(int, const char**)’:
tclmain.cc:167:1: error: ‘mainWin’ was not declared in this scope
 mainWin=0;
 ^

**Comment by highperformancecoder** [comment]
That means you have not installed Tk before install ecolab.

On Sun, Jan 17, 2016 at 03:49:37PM -0800, Alex Newman wrote:
> I was able to get ecolab installed. Still working on getting the full tests to run, however, now I have a problem with minksky itself, but I think I'm close.
> 
> ....
> g++ -c -fPIC -I. -I/home/vagrant/usr/ecolab/include -DHASH_TCL_hash -DHAVE_LONGLONG -DTR1 -I/home/vagrant/usr/ecolab/include -I/home/vagrant/usr/include -I/usr/local/include -I/opt/local/include -I/usr/X11R6/include -DZLIB -DXDR_PACK -DCONTIGUOUS -I/usr/include/tcl8.6 -DECOLAB_LIB=\"/home/vagrant/usr/ecolab/include\" -DNDEBUG -I/home/vagrant/usr/ecolab/include -std=c++11 -Ischema -Iengine -IGUI -O3 -UECOLAB_LIB -DECOLAB_LIB=\"library\" -pthread -I/usr/include/librsvg-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/libpng12 -I/usr/include/pixman-1 -I/usr/include/freetype2   -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -O3 -o tclmain.o tclmain.cc
> 
> tclmain.cc:56:3: error: ‘Tk_Window’ does not name a type
>    Tk_Window mainWin=0;
>    ^
> tclmain.cc: In function ‘int main(int, char**)’:
> tclmain.cc:123:10: error: ‘mainWin’ was not declared in this scope
>    while (mainWin) /* we are running GUI mode */
>           ^
> tclmain.cc: In function ‘void GUI(int, const char**)’:
> tclmain.cc:142:23: error: ‘Tk_Init’ was not declared in this scope
>    if (Tk_Init(interp())==TCL_ERROR || Tktable_Init(interp())==TCL_ERROR)
>                        ^
> tclmain.cc:158:3: error: ‘mainWin’ was not declared in this scope
>    mainWin = Tk_MainWindow(interp());
>    ^
> tclmain.cc:158:35: error: ‘Tk_MainWindow’ was not declared in this scope
>    mainWin = Tk_MainWindow(interp());
>                                    ^
> tclmain.cc: In function ‘void exit_ecolab(int, const char**)’:
> tclmain.cc:167:1: error: ‘mainWin’ was not declared in this scope
>  mainWin=0;
>  ^
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/minsky/issues/2

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by posix4e** [comment]
Gotcha.
