### ISSUE TITLE
RESTService - addVariable results in segmentation fault when incorrect type is passed

### ISSUE THREAD

**Issue by digiperfect-janak** [highperformancecoder/minsky#290]
`/minsky/canvas/addOperation [ "V1", "SomeUnknownType" ] `

should gracefully exit. It generates a segmentation fault. Perhaps same is the case with addOperation etc (not verified).

**Comment by highperformancecoder** [comment]
Problem found - "SomeUnknownType" gets translated to "undefined", which has no ports, and the code derefernces port[0].
