### ISSUE TITLE
Compilation error on json_spirit

### ISSUE THREAD

**Issue by alan-man** [highperformancecoder/minsky#298]
Hello,
I am trying to build Minsky on Ubuntu 18 but I am facing issues with json_spirit.
Here are the steps I followed : 
``` 
git clone git@github.com:highperformancecoder/json_spirit.git
cd json_spirit
mkdir build
cd build 
cmake .. 
sudo make install 
cd repos/minsky
make 
g++ -O3 -fPIC -I. -I/home/alant/repos/minsky/ecolab/include -DHASH_TCL_hash -DHAVE_LONGLONG -DTR1 -I/home/alant/repos/minsky/ecolab/include -I/home/alant/usr/include -I/usr/local/include -I/opt/local/include -I/usr/X11R6/include -DZLIB -DXDR_PACK  -DCAIRO -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -DCONTIGUOUS -DTK -I/usr/include/tcl8.6 -I/usr/include/tcl8.6 -DECOLAB_LIB=\"/home/alant/repos/minsky/ecolab/include\" -DNDEBUG -I/home/alant/repos/minsky/ecolab/include -I/usr/local/include/json_spirit -DJSON_SPIRIT_MVALUE_ENABLED -std=c++14 -Ischema -Iengine -Itensor -Imodel -Icertify/include -IRESTService -IRavelCAPI -O3 -UECOLAB_LIB -DECOLAB_LIB=\"library\" -Wno-unused-local-typedefs -pthread -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -DBOOST_SIGNALS_NO_DEPRECATION_WARNING tclmain.o minskyTCL.o wire.o item.o group.o minsky.o port.o operation.o variable.o switchIcon.o grid.o godleyTable.o cairoItems.o godleyIcon.o lock.o SVGItem.o plotWidget.o canvas.o panopticon.o godleyTableWindow.o ravelWrap.o sheet.o CSVDialog.o selection.o itemTab.o plotTab.o godleyTab.o variableInstanceList.o autoLayout.o userFunction.o userFunction_units.o parameterTab.o coverage.o derivative.o equationDisplay.o equations.o evalGodley.o evalOp.o flowCoef.o godleyExport.o latexMarkup.o variableValue.o node_latex.o node_matlab.o CSVParser.o minskyTensorOps.o mdlReader.o saver.o rungeKutta.o schema3.o schema2.o schema1.o schema0.o schemaHelper.o variableType.o operationType.o a85.o hypercube.o tensorOp.o xvector.o index.o interpolateHypercube.o RavelCAPI/libravelCAPI.a  -L/opt/local/lib/db48 -L. -L/home/alant/repos/minsky/ecolab/lib -lecolab -ldl -L/home/alant/repos/minsky/ecolab/lib -L/home/alant/usr/lib -L/usr/local/lib -L/opt/local/lib -L/usr/X11R6/lib  -lz -lcairo -ltk8.6 -ltkstub8.6 -lX11 -lXss -lXext -lXft -lfontconfig -lfreetype -lfontconfig -lpthread -ldl -lz -lpthread -lm -lX11 -lXss -lXext -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ltclstub8.6 -ldl -lz -lpthread -lm  -lm -LRavelCAPI -lravelCAPI -ljson_spirit -lboost_system -lboost_regex -lboost_date_time -lboost_program_options -lboost_filesystem -lboost_thread -lgsl -lgslcblas -lssl -lcrypto -lrsvg-2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lcairo  -o gui-tk/minsky
/usr/bin/ld: variableValue.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > classdesc::json<civita::NamedDimension>(civita::NamedDimension const&)':
variableValue.cc:(.text._ZN9classdesc4jsonIN6civita14NamedDimensionEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_[_ZN9classdesc4jsonIN6civita14NamedDimensionEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_]+0x148): undefined reference to `json_spirit::write(json_spirit::Value_impl<json_spirit::Config_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int)'
/usr/bin/ld: CSVParser.o: in function `void classdesc::json<std::vector<civita::NamedDimension, std::allocator<civita::NamedDimension> > >(std::vector<civita::NamedDimension, std::allocator<civita::NamedDimension> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
CSVParser.cc:(.text._ZN9classdesc4jsonISt6vectorIN6civita14NamedDimensionESaIS3_EEEEvRT_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN9classdesc4jsonISt6vectorIN6civita14NamedDimensionESaIS3_EEEEvRT_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x173): undefined reference to `json_spirit::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, json_spirit::Value_impl<json_spirit::Config_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'
collect2: error: ld returned 1 exit status

```
However, I have built the json_spirit lib : 
```
 ll /usr/local/lib
total 9024
drwxr-xr-x  3 root root     4096 Nov 22 18:40 ./
drwxr-xr-x 10 root root     4096 Feb  9  2021 ../
-rw-r--r--  1 root root  9225776 Nov 22 18:38 libjson_spirit.so
```
I have read that it's possible to build with header only json-spirit. But I don't see any instruction in compiling.md.
How could I do it ?
Best

**Comment by highperformancecoder** [comment]
`On Mon, Nov 22, 2021 at 07:32:47PM -0800, alan-man wrote:
> Hello,
> I am trying to build Minsky on Ubuntu 18 but I am facing issues with
> json_spirit.
> Here are the steps I followed :
> 
> git clone ***@***.***:highperformancecoder/json_spirit.git
> cd json_spirit
> mkdir build
> cd build
> cmake ..
> sudo make install

If you are doing this, then there is an additional step: run "ccmake ..",
and enable JSON_SPIRIT_MVALUE_ENABLED.

However, for master branch, lwhich I assume you've checked out below,
you can use the original json_spirit 4.08 available from various
sources, or use the prebuilt version from my OBS repository.

The revised json_spirit is for handling special floating point values,
and is needed in javascript version of Minsky - code currently
committed to the RESTService branch. On that branch, json_spirit is
included as a git submodule, so none of this will be necessary, once
that code gets merged to master.

> cd repos/minsky
> make
> g++ -O3 -fPIC -I. -I/home/alant/repos/minsky/ecolab/include -DHASH_TCL_hash -DHAVE_LONGLONG -DTR1 -I/home/alant/repos/minsky/ecolab/include -I/home/alant/usr/include -I/usr/local/include -I/opt/local/include -I/usr/X11R6/include -DZLIB -DXDR_PACK  -DCAIRO -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -DCONTIGUOUS -DTK -I/usr/include/tcl8.6 -I/usr/include/tcl8.6 -DECOLAB_LIB=\"/home/alant/repos/minsky/ecolab/include\" -DNDEBUG -I/home/alant/repos/minsky/ecolab/include -I/usr/local/include/json_spirit -DJSON_SPIRIT_MVALUE_ENABLED -std=c++14 -Ischema -Iengine -Itensor -Imodel -Icertify/include -IRESTService -IRavelCAPI -O3 -UECOLAB_LIB -DECOLAB_LIB=\"library\" -Wno-unused-local-typedefs -pthread -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/> include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -DBOOST_SIGNALS_NO_DEPRECATION_WARNING tclmain.o minskyTCL.o wire.o item.o group.o minsky.o port.o operation.o variable.o switchIcon.o grid.o godleyTable.o cairoItems.o godleyIcon.o lock.o SVGItem.o plotWidget.o canvas.o panopticon.o godleyTableWindow.o ravelWrap.o sheet.o CSVDialog.o selection.o itemTab.o plotTab.o godleyTab.o variableInstanceList.o autoLayout.o userFunction.o userFunction_units.o parameterTab.o coverage.o derivative.o equationDisplay.o equations.o evalGodley.o evalOp.o flowCoef.o godleyExport.o latexMarkup.o variableValue.o node_latex.o node_matlab.o CSVParser.o minskyTensorOps.o mdlReader.o saver.o rungeKutta.o schema3.o schema2.o schema1.o schema0.o schemaHelper.o variableType.o operationType.o a85.o hypercube.o tensorOp.o xvector.o index.o interpolateHypercube.o RavelCAPI/libravelCAPI.a  -L/opt/local/lib/db48 -L. -L/home/alant/repos/minsky/ecolab/lib -lecolab -ldl -L/home/alant/repos/min> sky/ecolab/lib -L/home/alant/usr/lib -L/usr/local/lib -L/opt/local/lib -L/usr/X11R6/lib  -lz -lcairo -ltk8.6 -ltkstub8.6 -lX11 -lXss -lXext -lXft -lfontconfig -lfreetype -lfontconfig -lpthread -ldl -lz -lpthread -lm -lX11 -lXss -lXext -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ltclstub8.6 -ldl -lz -lpthread -lm  -lm -LRavelCAPI -lravelCAPI -ljson_spirit -lboost_system -lboost_regex -lboost_date_time -lboost_program_options -lboost_filesystem -lboost_thread -lgsl -lgslcblas -lssl -lcrypto -lrsvg-2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lcairo  -o gui-tk/minsky
> /usr/bin/ld: variableValue.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > classdesc::json<civita::NamedDimension>(civita::NamedDimension const&)':
> variableValue.cc:(.text._ZN9classdesc4jsonIN6civita14NamedDimensionEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_[_ZN9classdesc4jsonIN6civita14NamedDimensionEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_]+0x148): undefined reference to `json_spirit::write(json_spirit::Value_impl<json_spirit::Config_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int)'
> /usr/bin/ld: CSVParser.o: in function `void classdesc::json<std::vector<civita::NamedDimension, std::allocator<civita::NamedDimension> > >(std::vector<civita::NamedDimension, std::allocator<civita::NamedDimension> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
> CSVParser.cc:(.text._ZN9classdesc4jsonISt6vectorIN6civita14NamedDimensionESaIS3_EEEEvRT_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN9classdesc4jsonISt6vectorIN6civita14NamedDimensionESaIS3_EEEEvRT_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x173): undefined reference to `json_spirit::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, json_spirit::Value_impl<json_spirit::Config_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'
> collect2: error: ld returned 1 exit status
> 
> 
> However, I have built the json_spirit lib :
> 
>  ll /usr/local/lib
> total 9024
> drwxr-xr-x  3 root root     4096 Nov 22 18:40 ./
> drwxr-xr-x 10 root root     4096 Feb  9  2021 ../
> -rw-r--r--  1 root root  9225776 Nov 22 18:38 libjson_spirit.so
> 
> I have read that it's possible to build with header only json-spirit. But I
> don't see any instruction in compiling.md.
> How could I do it ?
> Best
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. *
> 

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     ***@***.***
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by alan-man** [comment]
Works. 
Thanks
