### ISSUE TITLE
Cannot link across tk-table

### ISSUE THREAD

**Issue by posix4e** [highperformancecoder/minsky#3]
Am i forgetting a library 

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ make
...
g++ -O3 -fPIC -I. -I/home/vagrant/usr/ecolab/include -DHASH_TCL_hash -DHAVE_LONGLONG -DTR1 -I/home/vagrant/usr/ecolab/include -I/home/vagrant/usr/include -I/usr/local/include -I/opt/local/include -I/usr/X11R6/include -DZLIB -DXDR_PACK -DCAIRO -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12   -DCONTIGUOUS -DTK -I/usr/include/tcl8.6 -I/usr/include/tcl8.6 -DECOLAB_LIB=\"/home/vagrant/usr/ecolab/include\" -DNDEBUG -I/home/vagrant/usr/ecolab/include -std=c++11 -Ischema -Iengine -IGUI -O3 -UECOLAB_LIB -DECOLAB_LIB=\"library\" -pthread -I/usr/include/librsvg-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/libpng12 -I/usr/include/pixman-1 -I/usr/include/freetype2   -DBOOST_SIGNALS_NO_DEPRECATION_WARNING tclmain.o minskyTCL.o minsky.o godley.o portManager.o wire.o variable.o variableManager.o variableValue.o operation.o plotWidget.o cairoItems.o SVGItem.o equationDisplayItem.o godleyIcon.o groupIcon.o inGroupTest.o opVarBaseAttributes.o switchIcon.o evalOp.o equations.o derivative.o equationDisplay.o evalGodley.o latexMarkup.o flowCoef.o coverage.o schema0.o schema1.o variableType.o operationType.o  -L/opt/local/lib/db48 -L. -L/home/vagrant/usr/ecolab/lib/Tktable2.11 -L/home/vagrant/usr/lib/Tktable2.11 -L/usr/local/lib/Tktable2.11 -L/opt/local/lib/Tktable2.11 -L/usr/X11R6/lib/Tktable2.11 -lTktable2.11 -L/home/vagrant/usr/ecolab/lib -lecolab -ldl -L/home/vagrant/usr/ecolab/lib -L/home/vagrant/usr/lib -L/usr/local/lib -L/opt/local/lib -L/usr/X11R6/lib  -lz -lcairo   -ltk8.6 -ltkstub8.6 -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ltclstub8.6 -lX11 -lXss -lXext -lXft -lfontconfig -lfreetype -lpthread -ldl -lz -lpthread -lieee -lm  -lm -ljson_spirit -lboost_system -lboost_regex -lboost_date_time -lboost_program_options -lboost_filesystem -lgsl -lgslcblas   -lboost_thread  -lrsvg-2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lcairo -lgobject-2.0 -lglib-2.0    -o GUI/minsky
/usr/bin/ld: cannot find -lTktable2.11

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ dpkg --list|grep tk
ii  libatk-bridge2.0-0:amd64             2.10.2-2ubuntu1                     amd64        AT-SPI 2 toolkit bridge - shared library
ii  libatk1.0-0:amd64                    2.10.0-2ubuntu2                     amd64        ATK accessibility toolkit
ii  libatk1.0-data                       2.10.0-2ubuntu2                     all          Common files for the ATK accessibility toolkit
ii  libcanberra-gtk3-0:amd64             0.30-0ubuntu3                       amd64        GTK+ 3.0 helper for playing widget event sounds with libcanberra
ii  libcanberra-gtk3-module:amd64        0.30-0ubuntu3                       amd64        translates GTK3 widgets signals to event sounds
ii  libgtk-3-0:amd64                     3.10.8-0ubuntu1.6                   amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                         3.10.8-0ubuntu1.6                   amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common                      3.10.8-0ubuntu1.6                   all          common files for the GTK+ graphical user interface library
ii  libtk8.5:amd64                       8.5.15-2ubuntu3                     amd64        Tk toolkit for Tcl and X11 v8.5 - run-time files
ii  libtk8.6:amd64                       8.6.1-3ubuntu2                      amd64        Tk toolkit for Tcl and X11 v8.6 - run-time files
ii  tk                                   8.6.0+6ubuntu3                      amd64        Toolkit for Tcl and X11 (default version) - windowing shell
ii  tk-dev:amd64                         8.6.0+6ubuntu3                      amd64        Toolkit for Tcl and X11 (default version) - development files
ii  tk-table                             2.10-1                              amd64        Table extension for Tcl/Tk
ii  tk8.5                                8.5.15-2ubuntu3                     amd64        Tk toolkit for Tcl and X11, v8.5 - windowing shell
ii  tk8.5-dev:amd64                      8.5.15-2ubuntu3                     amd64        Tk toolkit for Tcl and X11, v8.5 - development files
ii  tk8.6                                8.6.1-3ubuntu2                      amd64        Tk toolkit for Tcl and X11 v8.6 - windowing shell
ii  tk8.6-dev:amd64                      8.6.1-3ubuntu2                      amd64        Tk toolkit for Tcl and X11 v8.6 - development files

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ locate -i tk-table
/pl/Library/Caches/Metadata/Safari/History/http:%2F%2Fpackages.ubuntu.com%2Ftrusty%2Ftk-table.webhistory
/pl/Library/Caches/Metadata/Safari/History/https:%2F%2Fwww.google.com%2Fsearch?client=safari&rls=en&q=-lTktable2.11&ie=UTF-8&oe=UTF-8%23q=-ltk-table.webhistory
/usr/share/doc/tk-table
/usr/share/doc/tk-table/README.blt
/usr/share/doc/tk-table/README.txt.gz
/usr/share/doc/tk-table/TODO.txt
/usr/share/doc/tk-table/changelog.Debian.gz
/usr/share/doc/tk-table/copyright
/usr/share/doc/tk-table/examples
/usr/share/doc/tk-table/examples/basic.tcl
/usr/share/doc/tk-table/examples/buttons.tcl
/usr/share/doc/tk-table/examples/command.tcl
/usr/share/doc/tk-table/examples/debug.tcl
/usr/share/doc/tk-table/examples/dynarows.tcl
/usr/share/doc/tk-table/examples/loadtable.tcl
/usr/share/doc/tk-table/examples/maxsize.tcl
/usr/share/doc/tk-table/examples/spreadsheet.tcl
/usr/share/doc/tk-table/examples/tcllogo.gif
/usr/share/doc/tk-table/examples/tktable.py
/usr/share/doc/tk-table/examples/valid.tcl
/var/cache/apt/archives/tk-table_2.10-1_amd64.deb
/var/lib/dpkg/info/tk-table.list
/var/lib/dpkg/info/tk-table.md5sums
vagrant@vagrant-ubuntu-trusty-64:/vagra

**Comment by highperformancecoder** [comment]
Yes - you need the TkTable package. You can get a prebuilt Ubuntu
version from
https://software.opensuse.org/download.html?project=home%3Ahpcoder1&package=tktable

You probably cannot install this in a docker container, however.

Alternatively, you can build TkTable from source code, and install
the .so file into ~/usr/lib. You'll need the TkTable.2.11.D3 tarball,
which I distribute from the Minsky SourceForge file release system.

Cheers

On Sun, Jan 17, 2016 at 04:31:48PM -0800, Alex Newman wrote:
> Am i forgetting a library 
> 
> vagrant@vagrant-ubuntu-trusty-64:/vagrant$ make
> ...
> g++ -O3 -fPIC -I. -I/home/vagrant/usr/ecolab/include -DHASH_TCL_hash -DHAVE_LONGLONG -DTR1 -I/home/vagrant/usr/ecolab/include -I/home/vagrant/usr/include -I/usr/local/include -I/opt/local/include -I/usr/X11R6/include -DZLIB -DXDR_PACK -DCAIRO -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12   -DCONTIGUOUS -DTK -I/usr/include/tcl8.6 -I/usr/include/tcl8.6 -DECOLAB_LIB=\"/home/vagrant/usr/ecolab/include\" -DNDEBUG -I/home/vagrant/usr/ecolab/include -std=c++11 -Ischema -Iengine -IGUI -O3 -UECOLAB_LIB -DECOLAB_LIB=\"library\" -pthread -I/usr/include/librsvg-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/libpng12 -I/usr/include/pixman-1 -I/usr/include/freetype2   -DBOOST_SIGNALS_NO_DEPRECATION_WARNING tclmain.o minskyTCL.o minsky.o godley.o portManager.o wire.o variable.o variabl
>  eManager
>  .o variableValue.o operation.o plotWidget.o cairoItems.o SVGItem.o equationDisplayItem.o godleyIcon.o groupIcon.o inGroupTest.o opVarBaseAttributes.o switchIcon.o evalOp.o equations.o derivative.o equationDisplay.o evalGodley.o latexMarkup.o flowCoef.o coverage.o schema0.o schema1.o variableType.o operationType.o  -L/opt/local/lib/db48 -L. -L/home/vagrant/usr/ecolab/lib/Tktable2.11 -L/home/vagrant/usr/lib/Tktable2.11 -L/usr/local/lib/Tktable2.11 -L/opt/local/lib/Tktable2.11 -L/usr/X11R6/lib/Tktable2.11 -lTktable2.11 -L/home/vagrant/usr/ecolab/lib -lecolab -ldl -L/home/vagrant/usr/ecolab/lib -L/home/vagrant/usr/lib -L/usr/local/lib -L/opt/local/lib -L/usr/X11R6/lib  -lz -lcairo   -ltk8.6 -ltkstub8.6 -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ltclstub8.6 -lX11 -lXss -lXext -lXft -lfontconfig -lfreetype -lpthread -ldl -lz -lpthread -lieee -lm  -lm -ljson_spirit -lboost_system -lboost_regex -lboost_date_time -lboost_program_options -lboost_filesystem -lgsl -lgslcblas   -lboost_thread
>    -lrsvg
>  -2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lcairo -lgobject-2.0 -lglib-2.0    -o GUI/minsky
> /usr/bin/ld: cannot find -lTktable2.11
> 
> vagrant@vagrant-ubuntu-trusty-64:/vagrant$ dpkg --list|grep tk
> ii  libatk-bridge2.0-0:amd64             2.10.2-2ubuntu1                     amd64        AT-SPI 2 toolkit bridge - shared library
> ii  libatk1.0-0:amd64                    2.10.0-2ubuntu2                     amd64        ATK accessibility toolkit
> ii  libatk1.0-data                       2.10.0-2ubuntu2                     all          Common files for the ATK accessibility toolkit
> ii  libcanberra-gtk3-0:amd64             0.30-0ubuntu3                       amd64        GTK+ 3.0 helper for playing widget event sounds with libcanberra
> ii  libcanberra-gtk3-module:amd64        0.30-0ubuntu3                       amd64        translates GTK3 widgets signals to event sounds
> ii  libgtk-3-0:amd64                     3.10.8-0ubuntu1.6                   amd64        GTK+ graphical user interface library
> ii  libgtk-3-bin                         3.10.8-0ubuntu1.6                   amd64        programs for the GTK+ graphical user interface library
> ii  libgtk-3-common                      3.10.8-0ubuntu1.6                   all          common files for the GTK+ graphical user interface library
> ii  libtk8.5:amd64                       8.5.15-2ubuntu3                     amd64        Tk toolkit for Tcl and X11 v8.5 - run-time files
> ii  libtk8.6:amd64                       8.6.1-3ubuntu2                      amd64        Tk toolkit for Tcl and X11 v8.6 - run-time files
> ii  tk                                   8.6.0+6ubuntu3                      amd64        Toolkit for Tcl and X11 (default version) - windowing shell
> ii  tk-dev:amd64                         8.6.0+6ubuntu3                      amd64        Toolkit for Tcl and X11 (default version) - development files
> ii  tk-table                             2.10-1                              amd64        Table extension for Tcl/Tk
> ii  tk8.5                                8.5.15-2ubuntu3                     amd64        Tk toolkit for Tcl and X11, v8.5 - windowing shell
> ii  tk8.5-dev:amd64                      8.5.15-2ubuntu3                     amd64        Tk toolkit for Tcl and X11, v8.5 - development files
> ii  tk8.6                                8.6.1-3ubuntu2                      amd64        Tk toolkit for Tcl and X11 v8.6 - windowing shell
> ii  tk8.6-dev:amd64                      8.6.1-3ubuntu2                      amd64        Tk toolkit for Tcl and X11 v8.6 - development files
> 
> vagrant@vagrant-ubuntu-trusty-64:/vagrant$ locate -i tk-table
> /pl/Library/Caches/Metadata/Safari/History/http:%2F%2Fpackages.ubuntu.com%2Ftrusty%2Ftk-table.webhistory
> /pl/Library/Caches/Metadata/Safari/History/https:%2F%2Fwww.google.com%2Fsearch?client=safari&rls=en&q=-lTktable2.11&ie=UTF-8&oe=UTF-8%23q=-ltk-table.webhistory
> /usr/share/doc/tk-table
> /usr/share/doc/tk-table/README.blt
> /usr/share/doc/tk-table/README.txt.gz
> /usr/share/doc/tk-table/TODO.txt
> /usr/share/doc/tk-table/changelog.Debian.gz
> /usr/share/doc/tk-table/copyright
> /usr/share/doc/tk-table/examples
> /usr/share/doc/tk-table/examples/basic.tcl
> /usr/share/doc/tk-table/examples/buttons.tcl
> /usr/share/doc/tk-table/examples/command.tcl
> /usr/share/doc/tk-table/examples/debug.tcl
> /usr/share/doc/tk-table/examples/dynarows.tcl
> /usr/share/doc/tk-table/examples/loadtable.tcl
> /usr/share/doc/tk-table/examples/maxsize.tcl
> /usr/share/doc/tk-table/examples/spreadsheet.tcl
> /usr/share/doc/tk-table/examples/tcllogo.gif
> /usr/share/doc/tk-table/examples/tktable.py
> /usr/share/doc/tk-table/examples/valid.tcl
> /var/cache/apt/archives/tk-table_2.10-1_amd64.deb
> /var/lib/dpkg/info/tk-table.list
> /var/lib/dpkg/info/tk-table.md5sums
> vagrant@vagrant-ubuntu-trusty-64:/vagra
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/minsky/issues/3

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------
