### ISSUE TITLE
Linux binary minsky requires --no-sandbox

### ISSUE THREAD

**Issue by aledomu** [highperformancecoder/minsky#331]
In version 3.0.0 with the new Electron frontend it does not start:

```
(node:32021) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
BadWindow (invalid Window parameter)
[32021:1127/230958.487590:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
```

Is this expected and should be documented or is this a bug?

**Comment by highperformancecoder** [comment]
[Some people have reported this error](https://sourceforge.net/p/minsky/tickets/1518/), but I haven't personally  seen it. Note that currently --disable_gpu flag is set on the minsky main process. Some stackoverflow posts indicate --no-sandbox might need to be set as well, as this is a Node/Chrom(e/ium) issue.

Could you please check whether the issue persists with minsky-3.1.0-beta.10? This has had an upgrade to electron. You could do this by installing the minsky-beta project (and minsky-beta-restservice)

**Comment by highperformancecoder** [comment]
Closing this as a duplicate.

**Comment by aledomu** [comment]
I can confirm it does not happen anymore in minsky-beta.

**Comment by johnnewto** [comment]
Same thing on 22.04 with minsky 3.18, 
 this worked, 
`sudo chown root:root  /usr/lib/minsky/chrome-sandbox`
`sudo chmod 4755  /usr/lib/minsky/chrome-sandbox`

**Comment by highperformancecoder** [comment]
Hi John - this issue is reported as https://sourceforge.net/p/minsky/tickets/1871/

We need to somehow set those permission bits in the OBS build script, or in the js-build target. I'll get to this issue eventually...
