### ISSUE TITLE
macOS build: cursor is misaligned with the canvas location passed to minsky when we 'click' on the canvas

### ISSUE THREAD

**Issue by aleith** [highperformancecoder/minsky#360]
__Basic Info:__
This only applies to the macOS builds (as far as I know).
Applies to latest release build 3.0.0 and beta version 3.1.0-beta.10

With regard to clicking to drag on ports & wires, and clicking and releasing to select nodes/objects/wires on the canvas, it seems that the canvas location passed to _minsky_ when we 'click' on the canvas (left or right click) or 'click & drag' on the canvas is not aligned to the cursor icon on screen. The gap is in the vertical dimension only, and is so far below the cursor "hotspot" (conventionally the tip of the black arrow and one pixel inside the white boarder) that it makes for very confusing and frustrating interactions with the canvas nodes for the unwitting (read novice user).

__Severity of bug / How it effects users:__
As a first time used in several years, I spent 30 minutes in a class I was trying to lead introducing fellow students to minsky wondering what was going on that I couldn't drag the output of a Parameter node to a graph input. So pretty bad until I twigged, but under pressure to show people features I soldiered on and we shared a PC user's screen instead.
I realised soon after when we ended the Zoom call, but even knowing this bug, it's tricky to adapt to it.

__Steps to reproduce:__
1. Attempt to click and drag from the output port (indicated with a black circle outline) of any node to drag out a wire.
2. Typically you will miss the circle in terms of the returned x/y location pair and if you are unlucky you may have been unwittingly in the bottom right "stretch node" target area and the result is a stretched node which you have to undo and reattempt to grab the wire from the output port.

__Workaround:__
1. move cursor to output port.
2. move it up until the "resize" hint disappears. 
3. click and drag and hopefully you adjusted your bow and arrow for the wind by just the right amount ;-)

__Documentation__
Movie demo of this and other related issues here: 
https://www.icloud.com/iclouddrive/096n82w-GXMbJxOpetcx9-2iQ

**Comment by highperformancecoder** [comment]
I believe this is now fixed, as of about version 3.7.

**Comment by highperformancecoder** [comment]
I believe this is now fixed, as of about version 3.7.
