### ISSUE TITLE
Remove assertion checks in rpm build

### ISSUE THREAD

**Issue by aledomu** [highperformancecoder/minsky#375]
This needs to be added to `minsky.spec` in the `minsky-restservice` package:

```
...
# Upstream recommends to turn off _GLIBCXX_ASSERTIONS.
# See: https://github.com/highperformancecoder/minsky/pull/370
%global optflags %optflags -U_GLIBCXX_ASSERTIONS

# required to exclude libXScrnSaver-devel on ppc64
...
```

I ask here because the spec file is not in the repository.

**Comment by highperformancecoder** [comment]
On Sun, Apr 09, 2023 at 03:54:39PM -0700, Alejandro Domínguez wrote:
> This needs to be added to minsky.spec in the minsky-restservice package:
> 
> ...
> # Upstream recommends to turn off _GLIBCXX_ASSERTIONS.
> # See: https://github.com/highperformancecoder/minsky/pull/370
> %global optflags %optflags -U_GLIBCXX_ASSERTIONS
> 
> # required to exclude libXScrnSaver-devel on ppc64
> ...
> 
> I ask here because the spec file is not in the repository.

No its not - its in the OBS repository: https://build.opensuse.org/package/show/home:hpcoder1/minsky-beta-restservice

Not sure if it has anything similar to a pull request mechanism, so
I'll take carriage of this.

I think OBS have started integrating github into their process - maybe it's time to do something about that.

Cheers


> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: 
> ***@***.***>
> 

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     ***@***.***
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by highperformancecoder** [comment]
Done
