### ISSUE TITLE
OBS has no release for Debian 12/Bookworm/Stable

### ISSUE THREAD

**Issue by citroboy** [highperformancecoder/minsky#392]
I tried installing the versions for 11 and Testing but no go.

**Comment by highperformancecoder** [comment]
I have just enabled Debian 12 builds.  Please wait 24 hours or so, then give it another try.

**Comment by citroboy** [comment]
I can install it now, thanks.

Unfortunately there is some issue with libfreetype that makes it unusable.
I loaded an existing model. It works until I zoom the canvas then trying to run the simulation yields:

BadWindow (invalid Window parameter)BadWindow (invalid Window parameter)BadWindow (invalid Window parameter)BadWindow (invalid Window parameter)BadWindow (invalid Window parameter)BadWindow (invalid Window parameter)BadWindow (invalid Window parameter)BadWindow (invalid Window parameter)
(minsky:727115): Pango-WARNING **: 18:38:13.021: failed to create cairo scaled font, expect ugly output. the offending font is 'Noto Sans 12'

(minsky:727115): Pango-WARNING **: 18:38:13.021: font_face status is: error occurred in libfreetype

(minsky:727115): Pango-WARNING **: 18:38:13.021: scaled_font status is: error occurred in libfreetype

Then everything goes screwy until I zoom back to the original size. The equations tab is still screwy though.

I thought to downgrade libfreetype but that makes apt want to uninstall... everything.

I tried changing fonts in minsky but the same happens with arial and DejaVu.

**Comment by highperformancecoder** [comment]
You've already tried the first things that came to my mind. If you're subscribed to my patreon account, you might be able to post a message to see if anyone has seen anything similar. Or you could try the minsky discussion lists on SourceForge.

However, I strongly suspect you are the first Minsky user on Debian 12, so don't be surprised if nobody answers. It may be that OBS's Debian 12 packages are somehow corrupted, and the situation will correct itself in time. How long has Debian 12 been out? I missed the announcement.

**Comment by citroboy** [comment]
Debian 12 snuck up on me too as I was previously running Testing. It seems rather than transition to the new Testing I have become Stable. The official release was June 10 apparently, so not that recent.

I might try installing libfreetype-dbg. Not sure why but maybe it'll help.
