### ISSUE TITLE
unittest library

### ISSUE THREAD

**Issue by posix4e** [highperformancecoder/minsky#4]
I'm having some issues with the build
https://travis-ci.org/posix4e/minsky/builds/103071618

I tried pre installing unittest-cpp but I'm not sure what version you used

**Comment by posix4e** [comment]
Oh here's the branch I rebased of my changes so far https://github.com/posix4e/minsky/tree/travis and its failing builds https://travis-ci.org/posix4e/minsky/builds.Thanks in advance!

**Comment by posix4e** [comment]
Obviously, we should probably keep everything tied to your repos if we want to  merge them :) I just did it for flexibility while building.

**Comment by highperformancecoder** [comment]
I use UnitTest++, as it is relatively sane, as compared with unittestcpp.

**Comment by highperformancecoder** [comment]
I doubt there is a precompiled package for it.

**Comment by posix4e** [comment]
What version
On Mon, Jan 18, 2016 at 3:12 PM Russell Standish <notifications@github.com>
wrote:

> I doubt there is a precompiled package for it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/highperformancecoder/minsky/issues/4#issuecomment-172678089>
> .
>
-- 

Sent from my mobile 5045076749
Alex Newman

**Comment by highperformancecoder** [comment]
I'm using 1.4

On Mon, Jan 18, 2016 at 04:00:38PM -0800, Alex Newman wrote:
> What version
> On Mon, Jan 18, 2016 at 3:12 PM Russell Standish <notifications@github.com>
> wrote:
> 
> > I doubt there is a precompiled package for it.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/highperformancecoder/minsky/issues/4#issuecomment-172678089>
> > .
> >
> -- 
> 
> Sent from my mobile 5045076749
> Alex Newman
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/minsky/issues/4#issuecomment-172688325

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------
