### ISSUE TITLE
Why is sourceforge still the canonical URL for this project?

### ISSUE THREAD

**Issue by davelab6** [highperformancecoder/minsky#438]
@highperformancecoder I'm a member of Steve's Mastermind group. I apologise that my question is a little presumptuous and entitled, but... Why is https://sourceforge.net/p/minsky still the canonical URL for this project? I was going to post a ticket there suggesting that the project move to Github because this is where most libre software developers collaborate daily, so its comfortable and familiar and productive to be here instead of there... but then while browsing what for me is a long-forgotten and clunky UI, I found that you had already mirrored the project here! haha :)

**Comment by highperformancecoder** [comment]
It's a good question, and the reasons are partially historical. "Mirrored" is the wrong word. The way it has panned out is that SF hosts the _user_ facing website, and Github the _developer_ facing website. SF has the FRS for distributing binaries, the issue reporting system, hosting user documentation and mailing lists (although this last functionality is somewhat surplanted by the Patreon community). By contrast, the github site hosts the source code repo, CI, code reviews and developer-facing documentation. 

Re migrating tickets from SF to GH, it is something I've considered. I have used both systems, and consider them much of a muchness. There's no particular advantage to the GH system. It is both a user and a developer functionality, and there are a lot more users than developers, so it just seems to be all downside to moving the ticket system. Plus, you'd lose all that history.

**Comment by davelab6** [comment]
Fair enough:)

For what it's worth, pages.github.com can do the user facing website better imho: a better user doc site using pages.github.com hosting, the gh repo releases tab can replace FRS for distributing binaries, users can be directed to the Discussions tab instead of Issues tab to keep that useful separation, and GH issues and discussions have mailing lists equivalency with email notifications that accept email replies. For history, sf is still there. 

Thanks for the quick and thoughtful reply!!

**Comment by highperformancecoder** [comment]
On Sat, Feb 03, 2024 at 10:21:45AM -0800, Dave Crossland wrote:
> Fair enough:)
> 
> For what it's worth, pages.github.com can do the user facing website better
> imho: a better user doc site using pages.github.com hosting, the gh repo
> releases tab can replace FRS for distributing binaries, users can be directed
> to the Discussions tab instead of Issues tab to keep that useful separation,
> and GH issues and discussions have mailing lists equivalency with email
> notifications that accept email replies. For history, sf is still there.
> 

All true, but IMHO much of a muchness with SF. There is a cost to
moving, not only the immediate cost of converting everything, but also
the "who moved my cheese" cost of things being different to what users
are used to. I'd need to see a significant advantage to outweigh that.


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     ***@***.***
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------
