### ISSUE TITLE
Connecting wires not showing correctly

### ISSUE THREAD

**Issue by davidadley** [highperformancecoder/minsky#47]
Hello,

I installed minksy on Ubuntu yakkety (16.10) but it appears that the connecting wires are not visible, see below:
![minskynonlinear](https://cloud.githubusercontent.com/assets/13313852/24076491/1e45830e-0c2a-11e7-8418-1a26e61515b7.png)

I've tried 1.53 (from source),1.54 (OpenSUSE package), 1.55 (from source) and github master from source. All with the same result. No errors appear on stdout except when compiled from github master:

`Error initialising Tk: window name "" already exists in parent(null)`

**Comment by davidadley** [comment]
I have looked a bit further and found that there are many errors in the `object browser` most are of the type shown below:
![minskyerrors](https://cloud.githubusercontent.com/assets/13313852/24076788/b1cec854-0c31-11e7-9ec8-9570d98763fa.png)

**Comment by highperformancecoder** [comment]
That is cetainly odd. The error message you quote doesn't have anything to do with your problem, AFAICT.

I assume when you say "OpenSUSE package", you mean the prebuilt Yakkety Yak binaries  from the OBS platform. If you're using a different Ubuntu release, or packages for another distribution, then you're bound to get problems.

That said, you reported problems with building from source code, so this might be a problem with your Tk installation. Try checking what version of Tk (and tk-dev) you have installed using the apt tool.

The other thing I can suggest is checking that there are wires in the model, and that they are visible. Open "Object Browser" from the file menu, then find "wires", then find @elem which will pull up a list of wires identified by a number. Click on a number to drill into the wire, then click on the "visible" attribute. These should all be 1. If they are 0, or there are no wires at all, then something is making them invisible, or deleting them, but that would just be weird.

If that all fails to identify the problem, I'll have to set up a Yakkety Yak virtual machine to see for myself. I'm actually an openSUSE guy, you see...

**Comment by highperformancecoder** [comment]
Re your last comment, the number of arguments for attributes should be either 0 or 1. 0 means a getter, 1 means a setter.

I suspect you've somehow picked up an incompatible TCL/Tk install. Try forcibly reinstalling those packages from apt...

**Comment by highperformancecoder** [comment]
Oh - ignore commands beginning with . when using the object browser. These are Tk window commands. Simplest thing for exploration is to open the blue "minsky->" object, as this is the top level C++ object. That way, your namespace is not polluted by native TCL/Tk stuff.

**Comment by davidadley** [comment]
Sorry I deleted that comment as I realised it wasn't useful. I can't recover it unfortunately.

There are 123 wires ranging from 355-478. A few wires have visible=0 but most appear to be visible=1. I used MinskyNonLinear.mky in the example folder, does it show up differently on your PC?

`apt-cache show tk`
> Package: tk
> Priority: optional
> Section: libs
> Installed-Size: 21
> Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
> Original-Maintainer: Debian Tcl/Tk Packagers <pkg-tcltk-devel@lists.alioth.debian.org>
> Architecture: i386
> Source: tcltk-defaults
> Version: 8.6.0+9
> Provides: wish
> Depends: tk8.6 (>= 8.6.0-2), tcl
> Breaks: tk8.3 (<< 8.3.5-16), tk8.4 (<< 8.4.20-2), tk8.5 (<< 8.5.14-3), tk8.6 (<< 8.6.0-2)
> Filename: pool/main/t/tcltk-defaults/tk_8.6.0+9_i386.deb
> Size: 3176
> MD5sum: 25f9f7fea497541cd74f8603d8e94aa7
> SHA1: 87fde8cf69bf79896e1da272e985f53d9f2a568f
> SHA256: 7f02667a654a389fb1c19928b5f76579987def46725699ae7cc004e12df41aeb
> Description-en: Toolkit for Tcl and X11 (default version) - windowing shell
>  Tk is a cross-platform graphical toolkit which provides the Motif
>  look-and-feel and is implemented using the Tcl scripting language.
>  .
>  This package is a dependency package, which depends on Debian's default
>  Tk version (currently 8.6).
> Description-md5: c18f13af983cc9102503e0f44f8d4b2e
> Multi-Arch: foreign
> Bugs: https://bugs.launchpad.net/ubuntu/+filebug
> Origin: Ubuntu
> Supported: 9m
> Task: ubuntu-desktop, ubuntu-usb, kubuntu-desktop, edubuntu-desktop, edubuntu-usb, xubuntu-core, xubuntu-desktop, mythbuntu-desktop, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntu-gnome-desktop, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop
> 

tk-dev is the same version

**Comment by highperformancecoder** [comment]
On Sat, Mar 18, 2017 at 04:47:25PM -0700, davidadley wrote:
> Sorry I deleted that comment as I realised it wasn't useful. I can't recover it unfortunately.
> 
> There are 123 wires ranging from 355-478. A few wires have visible=0
but most appear to be visible=1. 

That sounds about right.

> I used MinskyNonLinear.mky in the example folder, does it show up differently on your PC?
> 

Yes. All the wires show up on my computer. It's a weird one. Nobody
has ever reported this particular problem before - the inverse
sometimes where only wires show and no icons, but not where wires are MIA.

> `apt-cache show tk`
> > Package: tk
> > Priority: optional
> > Section: libs
> > Installed-Size: 21
> > Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
> > Original-Maintainer: Debian Tcl/Tk Packagers <pkg-tcltk-devel@lists.alioth.debian.org>
> > Architecture: i386
> > Source: tcltk-defaults
> > Version: 8.6.0+9
> > Provides: wish
> > Depends: tk8.6 (>= 8.6.0-2), tcl
> > Breaks: tk8.3 (<< 8.3.5-16), tk8.4 (<< 8.4.20-2), tk8.5 (<< 8.5.14-3), tk8.6 (<< 8.6.0-2)
> > Filename: pool/main/t/tcltk-defaults/tk_8.6.0+9_i386.deb
> > Size: 3176
> > MD5sum: 25f9f7fea497541cd74f8603d8e94aa7
> > SHA1: 87fde8cf69bf79896e1da272e985f53d9f2a568f
> > SHA256: 7f02667a654a389fb1c19928b5f76579987def46725699ae7cc004e12df41aeb
> > Description-en: Toolkit for Tcl and X11 (default version) - windowing shell
> >  Tk is a cross-platform graphical toolkit which provides the Motif
> >  look-and-feel and is implemented using the Tcl scripting language.
> >  .
> >  This package is a dependency package, which depends on Debian's default
> >  Tk version (currently 8.6).
> > Description-md5: c18f13af983cc9102503e0f44f8d4b2e
> > Multi-Arch: foreign
> > Bugs: https://bugs.launchpad.net/ubuntu/+filebug
> > Origin: Ubuntu
> > Supported: 9m
> > Task: ubuntu-desktop, ubuntu-usb, kubuntu-desktop, edubuntu-desktop, edubuntu-usb, xubuntu-core, xubuntu-desktop, mythbuntu-desktop, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntu-gnome-desktop, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop
> > 
> 
> tk-dev is the same version
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/minsky/issues/47#issuecomment-287583426

This looks alright too. Seems like I might need to spin up an Ubuntu
16.10 instance and probe what's going on...

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by highperformancecoder** [comment]
Hi David,

I just tried the Ubuntu 16.10 live image, installing the Minsky package. Wires showed up fine in this example.

Next, I'll try a full install, and then after that I'll update to the latest network release to see if that makes any difference.

**Comment by highperformancecoder** [comment]
Did all that, and the wires show up just fine on my Ubuntu 16.10 install.

**Comment by highperformancecoder** [comment]
Results of apt-cache show tk

Package: tk
Priority: optional
Section: libs
Installed-Size: 21
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Tcl/Tk Packagers <pkg-tcltk-devel@lists.alioth.debian.org>
Architecture: amd64
Source: tcltk-defaults
Version: 8.6.0+9
Provides: wish
Depends: tk8.6 (>= 8.6.0-2), tcl
Breaks: tk8.3 (<< 8.3.5-16), tk8.4 (<< 8.4.20-2), tk8.5 (<< 8.5.14-3), tk8.6 (<< 8.6.0-2)
Filename: pool/main/t/tcltk-defaults/tk_8.6.0+9_amd64.deb
Size: 3178
MD5sum: ac9c7f59c64d2e6574230de468c955cd
SHA1: 485767720808e8a66193e15eca22d0d177d49081
SHA256: a158d36580f6d66ee5765ee83a2e8721de9dfc3ee5159cc98d8796a096e45940
Description-en_AU: Toolkit for Tcl and X11 (default version) - windowing shell
 Tk is a cross-platform graphical toolkit which provides the Motif look-
 and-feel and is implemented using the Tcl scripting language.
 .
 This package is a dependency package, which depends on Debian's default Tk
 version (currently 8.6).
Description-md5: c18f13af983cc9102503e0f44f8d4b2e
Multi-Arch: foreign
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m
Task: ubuntu-desktop, ubuntu-usb, kubuntu-desktop, edubuntu-desktop, edubuntu-usb, xubuntu-core, xubuntu-desktop, mythbuntu-desktop, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntu-gnome-desktop, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop

Only difference I can see is that it looks like you're using the 32 bit version.

Could you please add the output of "apt-cache show minsky"?

**Comment by davidadley** [comment]
Hi,

That is strange. I'll try it on 16.04 tomorrow. 

`apt-cache show minsky` 

> Package: minsky
> Version: 1.54
> Architecture: i386
> Maintainer: Russell Standish <hpcoder@hpcoders.com.au>
> Installed-Size: 7932
> Depends: tktable, libblas3 | libblas.so.3, libboost-filesystem1.61.0, libboost-regex1.61.0, libboost-system1.61.0, libc6 (>= 2.4), libcairo2 (>= 1.10.0), libgcc1 (>= 1:4.2), libglib2.0-0 (>= 2.12.0), libgsl2, libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0), libreadline7 (>= 6.0), librsvg2-2 (>= 2.14.4), libstdc++6 (>= 5.2), libtcl8.6 (>= 8.6.0), libtk8.6 (>= 8.6.0), zlib1g (>= 1:1.1.4)
> Filename: ./i386/minsky_1.54_i386.deb
> Size: 1839486
> MD5sum: acbed3e7b86dbb9cdccd370a56a1db2d
> SHA1: 1593efe1f80b4a64ea62ba093fed3a9f8ee0977e
> SHA256: 0fdfc8554e563a5d0328d36afe9d025b8bf990ecc1ecafff6209f3e0699be840
> Section: sectionName
> Priority: optional
> Description: Graphical dynamical systems simulator oriented towards economics
> Description-md5: 31c35d1b0efc647fa26806ecfc25766c

**Comment by davidadley** [comment]
Wires are visible using 16.04 (amd64). 

Maybe it is a bug unique to my other computer system.
