### ISSUE TITLE
Equations disappear when I add stock variable as input

### ISSUE THREAD

**Issue by martinfreedman** [highperformancecoder/minsky#49]
Writing model but when I add a stock variable all equations on equation tab disappear.

Cannot add the model file here.

**Comment by highperformancecoder** [comment]
On Thu, Apr 06, 2017 at 08:24:20AM -0700, martinfreedman wrote:
> Writing model but when I add a stock variable all equations on equation tab disappear.
> 
> Cannot add the model file here.
> 

By "stock variable" do you mean an integration block? Could you be
seeing ticket #653?

Cheers

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by highperformancecoder** [comment]
Hi Martin, did you check whether your issue is [this one](https://sourceforge.net/p/minsky/tickets/653/)?

What is the answer to my question above?
