### ISSUE TITLE
Debian Testing package cannot be installed.

### ISSUE THREAD

**Issue by jrfern** [highperformancecoder/minsky#59]
Sorry if this is not the place to open this issue.

Tried to install the Debian Testing package from https://software.opensuse.org//download.html?project=home%3Ahpcoder1&package=minsky , unsuccessfully. The problem is that there is a dependency to libgsl2, which is not used anymore in Testing or Sid for most architectures. The current GNU Scientific Library (GSL) available is libgsl23.

**Comment by highperformancecoder** [comment]
Yes - its the right place to report it. I may not get to looking at it
until I'm back home next week.

I need to have the same package name for all debians an ubuntu. Why
doesn't libgsl2 select the latest available GSL 2.x?

Cheers

On Sun, Dec 10, 2017 at 10:02:25AM -0800, Juan Rafael Fernández wrote:
> Sorry if this is not the place to open this issue.
> 
> Tried to install the Debian Testing package from https://software.opensuse.org//download.html?project=home%3Ahpcoder1&package=minsky , unsuccessfully. The problem is that there is a dependency to libgsl2, which is not used anymore in Testing or Sid for most architectures. The current GNU Scientific Library (GSL) available is libgsl23.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/minsky/issues/59

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by jrfern** [comment]
Great to know!  Normally a change in the soname responds to an api change or the need to avoid conflicts, doesn't it?  I'll tell you what I could find as a user, not being a developer: the package page is https://tracker.debian.org/pkg/gsl . There you'll see that the change is not new and seems to be for good - you  can check that the newest Ubuntu versions use libgsl23 too https://launchpad.net/ubuntu/+source/gsl .

That's what I could find by myself. If needed we might contact the Debian and Ubuntu package maintainer (name and email available in the links above).

Apart from that, I found that tktable in the Opensuse repository belongs to the "sectionName (1)" section, not very standard, is it?

Cheers

**Comment by highperformancecoder** [comment]
On Mon, Dec 11, 2017 at 08:03:38AM -0800, Juan Rafael Fernández wrote:
> Great to know!  Normally a change in the soname responds to an api change or the need to avoid conflicts, doesn't it?  I'll tell you what I could find as a user, not being a developer: the package page is https://tracker.debian.org/pkg/gsl . There you'll see that the change is not new and seems to be for good - you  can check that the newest Ubuntu versions use libgsl23 too https://launchpad.net/ubuntu/+source/gsl .

I'll try changing the dependencies to libgsl23 when I get home next
week. So long as no distro drops off support in so doing, all is good.

> 
> That's what I could find by myself. If needed we might contact the Debian and Ubuntu package maintainer (name and email available in the links above).
> 
> Apart from that, I found that tktable in the Opensuse repository belongs to the "sectionName (1)" section, not very standard, is it?
>

Probably isn't. What changes to the debian.* files do you propose I do?

> Cheers
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/minsky/issues/59#issuecomment-350768957

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by highperformancecoder** [comment]
Changed it to section libdevel, as well as for other assorted projects
I manage on OBS.

I couldn't find an obvious distinction between the libs section and
the libdevel section - all libraries need header files to be useful.

Cheers

On Tue, Dec 12, 2017 at 04:20:07PM +0000, Juan Rafael Fernández wrote:
> > What changes to the debian.* files do you propose I do?
> 
> At least this, in debian/controls
> 
> `Section:lib`
> 
> because tktable is a library, I think.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/minsky/issues/59#issuecomment-351102393

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by jrfern** [comment]
Section libdevel is for the files needed to compile an application, lib is for the libraries necessary to run it. When run, applications don't use or need the header files.

Now it's me who is going on holiday, I'm looking forward to seeing progress in a usable minsky package when I'm back.

Cheers

**Comment by highperformancecoder** [comment]
And when the script produces both? 

On Sat, Dec 23, 2017 at 09:52:22AM -0800, Juan Rafael Fernández wrote:
> Section libdevel is for the files needed to compile an application, lib is for the libraries necessary to run it. When run, applications don't use or need the header files.
> 
> Now it's me who is going on holiday, I'm looking forward to seeing progress in a usable minsky package when I'm back.
> 
> Cheers
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/minsky/issues/59#issuecomment-353739428

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by jrfern** [comment]
> And when the script produces both?

I don't think compiling produces *.h, it uses them. That's the difference. Anyway

> I'll try changing the dependencies to libgsl23 when I get home next week.

Well, holidays have been over for some days now, did you find the time to test this change and recreate the package? If there's a problem between versions, maybe a 'depends: libgsl23 | libgsl2' could do the thing.

Saludos

**Comment by highperformancecoder** [comment]
Neither libgsl2-dev nor libgsl23-dev are available, Reverting back to libgsl0-dev

**Comment by jrfern** [comment]
@highperformancecoder, if I had access to your /debian directory, I might help with testing. I'm convinced that changing a line would make the package installable. You've got my email, to continue in private if you prefer so.

**Comment by highperformancecoder** [comment]
On Mon, Jan 29, 2018 at 01:06:14AM -0800, Juan Rafael Fernández wrote:
> @highperformancecoder, if I had access to your /debian directory, I might help with testing. I'm convinced that changing a line would make the package installable. You've got my email, to continue in private if you prefer so.

I don't think I have your email. I'm not sure what you mean by
"/debian directory". The relevant files can be found at
https://build.opensuse.org/package/show/home:hpcoder1/minsky. The
files all start with debian.*, except for the top level control file
called minsky.dsc.

If you sign up to OBS, you can fork the package, and play around with
modifying those files. There is no concept of pull request on OBS, like with
github, but you're welcome to email me patch files.

OTOH, if you find OBS a bit much, then you can try guessing what needs
to change in the debian.* files. These should correspond 1:1 with
similarly named files on a debian package system.

Cheers
-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by highperformancecoder** [comment]
Is this still an issue?

**Comment by jrfern** [comment]
No, it was fixed long ago (sorry, I didn't know the issue was still open).

By the way, I had an issue with the package signature (here I try Ubuntu 19):

> Get:7 http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_19.04  InRelease [1551 B]
> Err:7 http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_19.04  InRelease
>   The following signatures were invalid: EXPKEYSIG 5606C8D03F9E5FB8 home:hpcoder1 OBS Project <home:hpcoder1@build.opensuse.org>
> Reading package lists... Done
> W: GPG error: http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_19.04  InRelease: The following signatures were invalid: EXPKEYSIG 5606C8D03F9E5FB8 home:hpcoder1 OBS Project <home:hpcoder1@build.opensuse.org>
> E: The repository 'http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_19.04  InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
 
It seems your signature has changed. These lines fixes it (I use Debian Testing actually)

> sudo wget -nv http://download.opensuse.org/repositories/home:/hpcoder1/Debian_9.0/Release.key -O Release.key
> sudo apt-key add - < Release.key

Please feel free to close the issue.

**Comment by jrfern** [comment]
I found a new related bug: although the package says it depends on libreadline.so.8, minsky uses libreadline.so.7, and if it's not present in the system it fails to start. 

> $ minsky 
> minsky: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
> 

In Debian Testing libreadline.so.7 is available, but the version used is libreadline.so.8. I fixed the problem by reinstalling libreadline.so.7, but minsky should be really compiled against libreadline.so.8 to be uptodate.

**Comment by highperformancecoder** [comment]
> No, it was fixed long ago (sorry, I didn't know the issue was still open).
> 
> By the way, I had an issue with the package signature (here I try Ubuntu 19):
> 
> > Get:7 http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_19.04  InRelease [1551 B]
> > Err:7 http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_19.04  InRelease
> > The following signatures were invalid: EXPKEYSIG 5606C8D03F9E5FB8 home:hpcoder1 OBS Project home:hpcoder1@build.opensuse.org
> > Reading package lists... Done
> > W: GPG error: http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_19.04  InRelease: The following signatures were invalid: EXPKEYSIG 5606C8D03F9E5FB8 home:hpcoder1 OBS Project home:hpcoder1@build.opensuse.org
> > E: The repository 'http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_19.04  InRelease' is not signed.
> > N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> 
> It seems your signature has changed. These lines fixes it (I use Debian Testing actually)
> 
> > sudo wget -nv http://download.opensuse.org/repositories/home:/hpcoder1/Debian_9.0/Release.key -O Release.key
> > sudo apt-key add - < Release.key
> 
> Please feel free to close the issue.

I haven't changed my signature. I suspect that each release is signed separately for each version, but I don't know. I haven't really studied how OBS does its signatures.

**Comment by highperformancecoder** [comment]
> I found a new related bug: although the package says it depends on libreadline.so.8, minsky uses libreadline.so.7, and if it's not present in the system it fails to start.
> 
> > $ minsky
> > minsky: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
> 
> In Debian Testing libreadline.so.7 is available, but the version used is libreadline.so.8. I fixed the problem by reinstalling libreadline.so.7, but minsky should be really compiled against libreadline.so.8 to be uptodate.

Again that could be an OBS issue. It may be resolved next time the software is built.
Minsky just links against readline, whatever's the latest version for a particular distro.

**Comment by highperformancecoder** [comment]
I ran the obsCheck script on the latest Minsky release 2.17, which fires up an appropriate docker image for each distro, install Minsky and runs a smoke test, which is enough to establish that all dependencies are correctly installed with the package. I updated the Dockerfile script to point to Debian 10, which now passes. BTW - I hadn't added Debian Testing as a supported distro, which probably explains your problem - I ahve now added it, so you might like to try again in a day or so once it is all built.

**Comment by jrfern** [comment]
I waited for some days... same problem.
Maybe the devil is in the details, let's check again: 
1.- I modified the sources.list.d line, from xUbuntu_19.04/ to Debian_Testing/ and updated/upgraded.
2.- the package still claims to depend on libreadline8, but actually (as shown by ldd) the application depends on libreadline7, so I presume it is still compiled against libreadline7.
3.- The repository shows two versions of minsky available - 2.17.2 and 2.D17. Debian takes the latter as the newest one, is that correct?
Any ideas?

**Comment by highperformancecoder** [comment]
On Tue, Dec 10, 2019 at 11:24:09AM -0800, Juan Rafael Fernández wrote:
> I waited for some days... same problem.
> Maybe the devil is in the details, let's check again:
> 1.- I modified the sources.list.d line, from xUbuntu_19.04/ to Debian_Testing/
> and updated/upgraded.
> 2.- the package still claims to depend on libreadline8, but actually (as shown
> by ldd) the application depends on libreadline7, so I presume it is still
> compiled against libreadline7.

OBS has only recently added Debian Testing as an option. I'm guessing
Debian Testing is an unstable version of Debian, and potentially OBS
lags behind the official Debian Testing repo.

The configuration file doesn't mention a readline version:

 File debian.control of Package minsky

Source: minsky
Section: science
Priority: optional
Maintainer: Russell Standish <hpcoder@hpcoders.com.au>
Build-Depends: debhelper (>= 4.1.16), g++, tcl-dev,tk-dev, libcairo2-dev, zlib1g-dev, libreadline-dev, libgsl0-dev, libpango1.0-dev, exuberant-ctags, libdb-dev, libncurses5-dev, librsvg2-dev, json-spirit, libboost-dev, libboost-system-dev, libboost-regex-dev, libboost-date-time-dev, libboost-program-options-dev, libboost-filesystem-dev, libboost-thread-dev

Package: minsky
Architecture: any
Depends: ${shlibs:Depends}

Description: Graphical dynamical systems simulator oriented towards economics

shlibs:Depends runs a dpkg script to figure out what runtime library
package needs to be included, so that is possibly broken in Debian
Testing...


> 3.- The repository shows two versions of minsky available - 2.17.2 and 2.D17.
> Debian takes the latter as the newest one, is that correct?

The first one is a beta version (minsky-beta package). 2.17 is the latest
proper release (the D is just to trick Debian releases into relaising it is
the latest. The need for that will disappear if and when we ever move
to 3.x).


> Any ideas?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.*
> 

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------
